ALTER TABLE candidates ADD COLUMN IF NOT EXISTS resume_url TEXT;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS resume_text TEXT NOT NULL DEFAULT '';
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS ai_score NUMERIC(5, 2);
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS ai_report JSONB NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE jobs ADD COLUMN IF NOT EXISTS required_skills TEXT NOT NULL DEFAULT '';
